DELETE http://localhost:3003/api/blogs/6333fe04e71d67c932f7485b
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3Rpa2F5dHRhamEzIiwiaWQiOiI2MzMyZTZlMWZlMWM5NDJjMjU2N2Y0ZDkiLCJpYXQiOjE2NjQyODUxODd9.Szdex1K33I0LwEMQzv2OBYoZPV7JvayVR7kdAuMQPhc
